name: Build Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore FullSolution.sln

      - name: Build solution
        run: dotnet build FullSolution.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test FullSolution.sln --configuration Release --no-build --verbosity normal
