// Jenkinsfile
pipeline {
    agent any

    environment {
        SOLUTION_DIR = 'FullSolution'
        OUTPUT_DIR = "\\\\localhost\\Cursos\\Maestria Fullstack\\04 CI CD\\Builds\\${BUILD_NUMBER}\\"
    }

    stages {
        stage('Restore nuget packages') {
            steps {
                echo "Starting Restore nuget packages"
                dir("${env.SOLUTION_DIR}") {
                    bat 'dotnet restore'
                }
                echo "Finishing Restore nuget packages"
            }
        }
        stage('Clean FullSolution') {
            steps {
                echo "Starting Clean FullSolution"
                dir("${env.SOLUTION_DIR}") {
                    bat 'dotnet clean'
                }
                echo "Finishing Clean FullSolution"
            }
        }
        stage('Build FullSolution') {
            steps {
                echo "Starting Build FullSolution"
                dir("${env.SOLUTION_DIR}") {
                    bat 'dotnet build'
                }
                echo "Finishing Build FullSolution"
            }
        }

        stage('Test FullSolution') {
            steps {
                echo "Starting Test FullSolution"
                dir("${env.SOLUTION_DIR}") {
                    bat 'dotnet test --no-build --verbosity normal'
                }
                echo "Finishing Test FullSolution"
            }
        }

        stage('Deploy AdminSolution') {
            steps {
                echo "Starting Deploy AdminSolution"
                dir("${env.SOLUTION_DIR}/AdminSolution") {
                    bat "dotnet publish -c Release -o \"${env.OUTPUT_DIR}\\AdminSolution\""
                }
                echo "Finishing Deploy AdminSolution"
            }
        }
        stage('Deploy MainSolution') {
            steps {
                echo "Starting Deploy MainSolution"
                dir("${env.SOLUTION_DIR}/MainSolution") {
                    bat "dotnet publish -c Release -o \"${env.OUTPUT_DIR}MainSolution\""
                }
                echo "Finishing Deploy MainSolution"
            }
        }
        stage('Deploy SecuritySolution') {
            steps {
                echo "Starting Deploy SecuritySolution"
                dir("${env.SOLUTION_DIR}/SecuritySolution") {
                    bat "dotnet publish -c Release -o \"${env.OUTPUT_DIR}SecuritySolution\""
                }
                echo "Finishing Deploy SecuritySolution"
            }
        }
    }
  }